// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/TimofeyChernyshev/comment-post-system/internal/domain"
)

type CommentConnection struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Cursor string          `json:"cursor"`
	Node   *domain.Comment `json:"node"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PostConnection struct {
	Edges    []*PostEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type PostEdge struct {
	Cursor string       `json:"cursor"`
	Node   *domain.Post `json:"node"`
}

type Query struct {
}

type Subscription struct {
}
