// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package graph is a generated GoMock package.
package graph

import (
	context "context"
	reflect "reflect"

	domain "github.com/TimofeyChernyshev/comment-post-system/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockPostService is a mock of PostService interface.
type MockPostService struct {
	ctrl     *gomock.Controller
	recorder *MockPostServiceMockRecorder
}

// MockPostServiceMockRecorder is the mock recorder for MockPostService.
type MockPostServiceMockRecorder struct {
	mock *MockPostService
}

// NewMockPostService creates a new mock instance.
func NewMockPostService(ctrl *gomock.Controller) *MockPostService {
	mock := &MockPostService{ctrl: ctrl}
	mock.recorder = &MockPostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostService) EXPECT() *MockPostServiceMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockPostService) CreatePost(ctx context.Context, params domain.PostCreationParams) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, params)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostServiceMockRecorder) CreatePost(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPostService)(nil).CreatePost), ctx, params)
}

// DisableComments mocks base method.
func (m *MockPostService) DisableComments(ctx context.Context, actorID, postID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableComments", ctx, actorID, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableComments indicates an expected call of DisableComments.
func (mr *MockPostServiceMockRecorder) DisableComments(ctx, actorID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableComments", reflect.TypeOf((*MockPostService)(nil).DisableComments), ctx, actorID, postID)
}

// GetPost mocks base method.
func (m *MockPostService) GetPost(ctx context.Context, id string) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", ctx, id)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockPostServiceMockRecorder) GetPost(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockPostService)(nil).GetPost), ctx, id)
}

// ListPosts mocks base method.
func (m *MockPostService) ListPosts(ctx context.Context, first int, after *string) ([]*domain.Post, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPosts", ctx, first, after)
	ret0, _ := ret[0].([]*domain.Post)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPosts indicates an expected call of ListPosts.
func (mr *MockPostServiceMockRecorder) ListPosts(ctx, first, after interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPosts", reflect.TypeOf((*MockPostService)(nil).ListPosts), ctx, first, after)
}

// MockCommentService is a mock of CommentService interface.
type MockCommentService struct {
	ctrl     *gomock.Controller
	recorder *MockCommentServiceMockRecorder
}

// MockCommentServiceMockRecorder is the mock recorder for MockCommentService.
type MockCommentServiceMockRecorder struct {
	mock *MockCommentService
}

// NewMockCommentService creates a new mock instance.
func NewMockCommentService(ctrl *gomock.Controller) *MockCommentService {
	mock := &MockCommentService{ctrl: ctrl}
	mock.recorder = &MockCommentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentService) EXPECT() *MockCommentServiceMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockCommentService) CreateComment(ctx context.Context, params domain.CommentCreationParams) (*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, params)
	ret0, _ := ret[0].(*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockCommentServiceMockRecorder) CreateComment(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockCommentService)(nil).CreateComment), ctx, params)
}

// GetComment mocks base method.
func (m *MockCommentService) GetComment(ctx context.Context, id string) (*domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComment", ctx, id)
	ret0, _ := ret[0].(*domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComment indicates an expected call of GetComment.
func (mr *MockCommentServiceMockRecorder) GetComment(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComment", reflect.TypeOf((*MockCommentService)(nil).GetComment), ctx, id)
}

// ListChildrenBatch mocks base method.
func (m *MockCommentService) ListChildrenBatch(ctx context.Context, parentIDs []string, firsts []int, afters []*string) (map[string][]*domain.Comment, map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChildrenBatch", ctx, parentIDs, firsts, afters)
	ret0, _ := ret[0].(map[string][]*domain.Comment)
	ret1, _ := ret[1].(map[string]bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListChildrenBatch indicates an expected call of ListChildrenBatch.
func (mr *MockCommentServiceMockRecorder) ListChildrenBatch(ctx, parentIDs, firsts, afters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChildrenBatch", reflect.TypeOf((*MockCommentService)(nil).ListChildrenBatch), ctx, parentIDs, firsts, afters)
}

// ListComments mocks base method.
func (m *MockCommentService) ListComments(ctx context.Context, postID string, parentID *string, first int, after *string) ([]*domain.Comment, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComments", ctx, postID, parentID, first, after)
	ret0, _ := ret[0].([]*domain.Comment)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListComments indicates an expected call of ListComments.
func (mr *MockCommentServiceMockRecorder) ListComments(ctx, postID, parentID, first, after interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MockCommentService)(nil).ListComments), ctx, postID, parentID, first, after)
}

// MockSubscriptionManager is a mock of SubscriptionManager interface.
type MockSubscriptionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionManagerMockRecorder
}

// MockSubscriptionManagerMockRecorder is the mock recorder for MockSubscriptionManager.
type MockSubscriptionManagerMockRecorder struct {
	mock *MockSubscriptionManager
}

// NewMockSubscriptionManager creates a new mock instance.
func NewMockSubscriptionManager(ctrl *gomock.Controller) *MockSubscriptionManager {
	mock := &MockSubscriptionManager{ctrl: ctrl}
	mock.recorder = &MockSubscriptionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionManager) EXPECT() *MockSubscriptionManagerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSubscriptionManager) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockSubscriptionManagerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSubscriptionManager)(nil).Close))
}

// PublishComment mocks base method.
func (m *MockSubscriptionManager) PublishComment(comment *domain.Comment) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PublishComment", comment)
}

// PublishComment indicates an expected call of PublishComment.
func (mr *MockSubscriptionManagerMockRecorder) PublishComment(comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishComment", reflect.TypeOf((*MockSubscriptionManager)(nil).PublishComment), comment)
}

// SubscribeComments mocks base method.
func (m *MockSubscriptionManager) SubscribeComments(postID string) (<-chan *domain.Comment, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeComments", postID)
	ret0, _ := ret[0].(<-chan *domain.Comment)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SubscribeComments indicates an expected call of SubscribeComments.
func (mr *MockSubscriptionManagerMockRecorder) SubscribeComments(postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeComments", reflect.TypeOf((*MockSubscriptionManager)(nil).SubscribeComments), postID)
}
