package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/TimofeyChernyshev/comment-post-system/internal/domain"
	"github.com/TimofeyChernyshev/comment-post-system/internal/infrastructure/graphql/graph/model"
)

// Children is the resolver for the children field.
func (r *commentResolver) Children(ctx context.Context, obj *domain.Comment, first int32, after *string) (*model.CommentConnection, error) {
	loaders := Loaders(ctx)

	result, err := loaders.commentChildren.Load(ctx, ChildrenKey{
		ParentID: obj.ID,
		First:    int(first),
		After:    after,
	})()
	if err != nil {
		return nil, fmt.Errorf("cannot load comments: %w", err)
	}

	return toCommentConnection(result.Items, result.HasNextPage), nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, params domain.PostCreationParams) (*domain.Post, error) {
	post, err := r.PostService.CreatePost(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("cannot create post: %w", err)
	}

	return post, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, params domain.CommentCreationParams) (*domain.Comment, error) {
	comment, err := r.CommentService.CreateComment(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("cannot create commen: %w", err)
	}

	r.SubscriptionManager.PublishComment(comment)

	return comment, nil
}

// DisableComments is the resolver for the disableComments field.
func (r *mutationResolver) DisableComments(ctx context.Context, postID string, actorID string) (bool, error) {
	err := r.PostService.DisableComments(ctx, actorID, postID)
	if err != nil {
		return false, fmt.Errorf("cannot disable comments: %w", err)
	}

	return true, nil
}

// Comments is the resolver for the comments field. Returns root comments
func (r *postResolver) Comments(ctx context.Context, obj *domain.Post, first int32, after *string) (*model.CommentConnection, error) {
	comments, hasNextPage, err := r.CommentService.ListComments(ctx, obj.ID, nil, int(first), after)
	if err != nil {
		return nil, fmt.Errorf("cannot list comments: %w", err)
	}

	return toCommentConnection(comments, hasNextPage), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first int32, after *string) (*model.PostConnection, error) {
	posts, hasNextPage, err := r.PostService.ListPosts(ctx, int(first), after)
	if err != nil {
		return nil, fmt.Errorf("cannot list posts: %w", err)
	}

	return toPostConnection(posts, hasNextPage), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*domain.Post, error) {
	post, err := r.PostService.GetPost(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("cannot get post: %w", err)
	}

	return post, nil
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id string) (*domain.Comment, error) {
	comment, err := r.CommentService.GetComment(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("cannot get comment: %w", err)
	}

	return comment, nil
}

// Comments is the resolver for the comments field.
func (r *subscriptionResolver) Comments(ctx context.Context, postID string) (<-chan *domain.Comment, error) {
	ch, unsubscribe, err := r.SubscriptionManager.SubscribeComments(postID)
	if err != nil {
		return nil, fmt.Errorf("cannot subscribe on comments: %w", err)
	}

	go func() {
		<-ctx.Done()
		unsubscribe()
	}()

	return ch, nil
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
